### ISSUE TITLE
Runes should be documented on the Curse page

### ISSUE THREAD

**Issue by TheFurtivePygmy** [Xilef11/runesofwizardry-classics#10]
There's no listing of the runes or what they do, aside from the staff tooltips, anywhere in existence as far as I can tell. Even the original Runic Dust thread doesn't seem to actually say what the mod does. It's not uncommon for Minecraft mods to be poorly documented but this might be the worst case I've seen.

For the sake of bringing in new players, please consider documenting the runes, even if it's only on the Curse page.

**Comment by Xilef11** [comment]
I listed the runes and inscriptions on the Curse page as well as on the README here. 

There is a proper "guide book" planned with images of the runes, but making GUIs is painful, so if you have suggestions feel free to voice them. 

I could also enable the wiki, but I don't have time to write proper documentation there on top of maintaining the mod

**Comment by scottosx** [comment]
You should do what many others are and use a variation on the Lexicon code from Vazkii https://github.com/Vazkii/Botania/tree/96c352616e42f759714941909e6c8c40213b711a/src/main/java/vazkii/botania/common/lexicon  Astral Sorcery and Totemic do this for instance if you want to see simplified versions.

**Comment by Xilef11** [comment]
I'm currently working on implementing one with guide-api.

**Comment by Xilef11** [comment]
there is a proper ingame guide now, using Guide-API.
