### ISSUE TITLE
game crashes after using ressurection rune

### ISSUE THREAD

**Issue by matyklugDebbuged** [Xilef11/runesofwizardry-classics#15]

**Comment by Xilef11** [comment]
Log and crash report please. 

In the meantime, you can disable the rune in the config (in the `Debug` category)

**Comment by Xilef11** [comment]
Can't reproduce with the latest version (1.12.2-0.5.8) and vanilla mobs. However, some modded mobs have been known to break this rune. 
Please reopen with a log and crash report if it happens again.
