### ISSUE TITLE
Inscriptions (Leap II)

### ISSUE THREAD

**Issue by SafsoufaS** [Xilef11/runesofwizardry-classics#19]
Whenever I create the proper runes and sacrifice the correct materials for the Leap II inscription, I get a Leap I back instead. I've tried several times but every time I follow the instructions for the Leap II Charge I get back Leap I. I don't know what's happening but I should be getting back a charged Leap II, and a charged Leap I.

**Comment by Xilef11** [comment]
Fixed by [f4f80c82b](https://github.com/Xilef11/runesofwizardry-classics/commit/f4f80c82b8dfe761015782c1b2bc31a5076c1a82). will be in the next release
