### ISSUE TITLE
Spirit Tools symbol crashes my game.

### ISSUE THREAD

**Issue by elucent** [Xilef11/runesofwizardry-classics#4]
Crashlog: https://gist.github.com/elucent/225cfb82113029f1aecab887f34e0314

Nice job with the mod by the way! Most of the symbols I've tested have been working, though there are quite a few I haven't checked due to my lack of understanding of what they do. As always, any in-game documentation would be great, but you've done a great job regardless!

**Comment by elucent** [comment]
This appears to only happen when using the sacrifice negator.

**Comment by Xilef11** [comment]
For the documentation, the tooltip of the runic dictionary should have a description (hold shift for more), but if there are specific ones that need to be improved, please let me know

**Comment by elucent** [comment]
Yeah, I didn't realize that the tooltip had a description until later. That works, if a little more inconvenient than the original mod. Still, I can see where you're coming from, I'm not a fan of GUIs either. :P
